"use client";

import { useState } from "react";

interface CoverImageProps {
  src: string;
  alt: string;
  className?: string;
  /** Use smaller thumbnail variant for card grids */
  thumbnail?: boolean;
  /** Above-the-fold image — disables lazy loading */
  priority?: boolean;
}

function getThumbUrl(src: string): string {
  // For WebP files generated by our pipeline: file.webp → file_thumb.webp
  const match = src.match(/^(.+)\.(webp|jpg|jpeg|png)(\?.*)?$/);
  if (match) return `${match[1]}_thumb.${match[2]}${match[3] || ""}`;
  return src;
}

export default function CoverImage({
  src,
  alt,
  className = "",
  thumbnail = false,
  priority = false,
}: CoverImageProps) {
  const [loaded, setLoaded] = useState(false);

  const finalSrc = thumbnail ? getThumbUrl(src) : src;

  return (
    <img
      src={finalSrc}
      alt={alt}
      loading={priority ? "eager" : "lazy"}
      decoding="async"
      fetchPriority={priority ? "high" : "auto"}
      onLoad={() => setLoaded(true)}
      onError={(e) => {
        // Fallback to original URL if thumbnail doesn't exist
        if (thumbnail && e.currentTarget.src !== src) {
          e.currentTarget.src = src;
        }
      }}
      className={`${className} transition-opacity duration-500 ${loaded ? "opacity-100" : "opacity-0"}`}
    />
  );
}
